mailinglist/urls.py
from django.urls import path

from mailinglist import views

app_name = "mailinglist"

urlpatterns = [
    path("", views.MailingListListView.as_view(), name="mailinglist_list"),
    path("new", views.CreateMailingListView.as_view(), name="create_mailinglist"),
    path(
        "<uuid:pk>/delete",
        views.DeleteMailingListView.as_view(),
        name="delete_mailinglist",
    ),
    path(
        "<uuid:pk>/manage",
        views.MailingListDetailView.as_view(),
        name="manage_mailinglist",
    ),
    path(
        "<uuid:mailinglist_id>/subscribe",
        views.SubscribeToMailingListView.as_view(),
        name="subscribe",
    ),
    path(
        "<uuid:pk>/thankyou",
        views.ThankYouForSubscribingView.as_view(),
        name="subscriber_thankyou",
    ),
    path(
        "subscribe/confirmation/<uuid:pk>",
        views.ConfirmSubscriptionView.as_view(),
        name="confirm_subscription",
    ),
    path("unsubscribe/<uuid:pk>", views.UnsubscribeView.as_view(), name="unsubscribe"),
    path(
        "<uuid:mailinglist_id>/message/new",
        views.CreateMessageView.as_view(),
        name="create_message",
    ),
    path("message/<uuid:pk>", views.MessageDetailView.as_view(), name="view_message"),
    path(
        "api/v1/mailing-list",
        views.MailingListCreateListView.as_view(),
        name="api-mailing-list-list",
    ),
    path(
        "api/v1/mailinglist/<uuid:pk>",
        views.MailingListRetrieveUpdateDestroyView.as_view(),
        name="api-mailing-list-detail",
    ),
    path(
        "api/v1/mailinglist/<uuid:mailing_list_id>/subscribers",
        views.SubscriberListCreateView.as_view(),
        name="api-subscriber-list",
    ),
    path(
        "api/v1/subscriber/<uuid:pk>",
        views.SubscriberRetrieveUpdateDestroyView.as_view(),
        name="api-subscriber-detail",
    ),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path

import mailinglist.urls
import user.urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include(user.urls, namespace="user")),
    path("mailinglist/", include(mailinglist.urls, namespace="mailinglist")),
]

user/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import RegisterView

app_name = "user"

urlpatterns = [
    path("login", LoginView.as_view(), name="login"),
    path("logout", LogoutView.as_view(), name="logout"),
    path("register", RegisterView.as_view(), name="register"),
]

templates/includes/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'mailinglist:mailinglist_list' %}">Django Mailer</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mailinglist:mailinglist_list' %}">Mailing Lists</a>
                    </li>
                {% endif %}
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:register' %}">Register</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>